name: From Jira Dispatch

on:
  repository_dispatch:
    types: [jira-transition]

jobs:
  run-on-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Run CI/CD
        run: echo "🚀 Running pipeline on ${{ github.event.client_payload.branch_name }}"
