name: Jira Transition Workflow

on:
  repository_dispatch:
    types: [jira-transition]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload
        run: |
          echo "Issue: ${{ github.event.client_payload.issue_key }}"
          echo "Branch: ${{ github.event.client_payload.branch_name }}"
